version: '3'

services:
    mysql:
        container_name: mysql
        image: mysql:5.7
        volumes:
            - mysql_data2:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: reservations-db
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    keycloak:
        container_name: keycloak
        image: quay.io/keycloak/keycloak:21.1.1
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        ports:
            - "9090:8080"
        command:
            - "start-dev"